version: "3.8"

# On your prod server, copy this as docker-compose.override.yml, then fill it out for prod with actual secrets.  Safest is to just randomly generate a UUID for:
# MYSQL_USER, MYSQL_PASSWORD, MYSQL_ROOT_PASSWORD, API_KEY
# Also set up your discord webhooks for EC Chat and Feedback from the website
# Make sure that same API_KEY is used in your log-reader's config.json.
# Don't keep this in your local, though, or you'll probably start double writing to the prod DB
services:
  server:
    environment:
      # DISCORD_FEEDBACK_WEBHOOK: https://discord.com/api/webhooks/somewebhook/morewebhookinfo1
      # DISCORD_EC_CHAT_WEBHOOK: https://discord.com/api/webhooks/somewebhook/morewebhookinfo2
      # DISCORD_GENERAL_WEBHOOK: https://discord.com/api/webhooks/somewebhook/morewebhookinfo3
      # MYSQL_HOST: quarm.dinodna.dev
      # MYSQL_USER: mysql
      # MYSQL_PASSWORD: mysql
      # API_KEY: super-secret-api-key
  mysql:
    environment:
      # MYSQL_USER: mysql
      # MYSQL_PASSWORD: mysql
      # MYSQL_ROOT_PASSWORD: mysql